spring:
  application:
    name: otus-health-app
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5444/otus}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:postgres}

springdoc:
  show-actuator: true
  use-management-port: true
management:
  server:
    port: 9090
  endpoints:
    web:
      exposure:
        include: openapi, swagger-ui
